# -*- coding: utf-8 -*-
"""E commerce project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vh6A783uIgDu2GbZiavk7l_0y45OGcDD
"""

import pandas as pd
import numpy as np
print("Pandas and NumPy imported successfully!")

import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme(style="whitegrid")
print("Visualization libraries imported successfully!")

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
print("Data preparation tools imported successfully!")

from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
print("Machine learning models imported successfully!")

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix
)

print("Evaluation metrics imported successfully!")

from google.colab import files

uploaded = files.upload()

file_name = 'ecommerce_customers_200_clean.csv'

df = pd.read_csv(file_name)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

display(df.head())

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print(df.columns.tolist())

display(df.dtypes.to_frame("Data Type"))

display(df.isna().sum().to_frame("Missing Values"))

print("Duplicate rows:", df.duplicated().sum())

display(df.describe(include="all").T)

# ==========================================================
# Topic: Regression Target
# Description:
# A regression problem predicts a continuous numerical value.
# In this project, the value we want to predict is Annual_Spending.
#
# Key idea:
# Annual_Spending is the target variable for regression.
# ==========================================================

regression_target = "Annual_Spending"

print("Regression target:", regression_target)

# ==========================================================
# Topic: Classification Target
# Description:
# A classification problem predicts a category or class.
# In this project, Churn contains 0 or 1.
#
# Key idea:
# Churn is the target variable for classification.
# ==========================================================

classification_target = "Churn"

print("Classification target:", classification_target)

# ==========================================================
# Topic: Checking Churn Classes
# Description:
# value_counts() counts how many customers belong to each churn class.
# 0 represents No Churn and 1 represents Churn.
#
# Key idea:
# This helps us understand the distribution of the classification target.
# ==========================================================

display(
    df["Churn"]
    .value_counts()
    .rename(index={0: "No Churn", 1: "Churn"})
)

# ==========================================================
# Topic: Annual Spending Distribution
# Description:
# A histogram shows how Annual_Spending values are distributed.
# The KDE curve gives an additional view of the distribution.
#
# Key idea:
# A distribution plot helps us see the range and pattern of customer spending.
# ==========================================================

plt.figure(figsize=(8, 5))
sns.histplot(df["Annual_Spending"], kde=True)
plt.title("Annual Spending Distribution")
plt.xlabel("Annual Spending (₹)")
plt.show()

# ==========================================================
# Topic: Income vs Annual Spending
# Description:
# A scatter plot shows the relationship between Income and Annual_Spending.
# Each point represents one customer.
# The colour separates customers by Membership_Type.
#
# Key idea:
# Charts can help us notice possible relationships between variables.
# ==========================================================

plt.figure(figsize=(8, 5))
sns.scatterplot(
    data=df,
    x="Income",
    y="Annual_Spending",
    hue="Membership_Type"
)
plt.title("Income vs Annual Spending")
plt.show()

plt.figure(figsize=(6, 4))
sns.countplot(data=df, x="Churn")
plt.xticks([0, 1], ["No Churn", "Churn"])
plt.title("Churn Distribution")
plt.show()

plt.figure(figsize=(8, 5))
sns.boxplot(data=df, x="Membership_Type", y="Annual_Spending")
plt.title("Annual Spending by Membership")
plt.show()

regression_features = [
    "Age", "Gender", "City_Tier", "Income", "Tenure_Months",
    "Visits_Per_Month", "Products_Bought", "Avg_Order_Value",
    "Discount_Usage_Rate", "Cart_Abandonment_Rate", "Reviews_Given",
    "Support_Tickets", "Days_Since_Last_Purchase",
    "Membership_Type", "Preferred_Category"
]

X_reg = df[regression_features]

print("Number of input features:", X_reg.shape[1])
display(X_reg.head())

y_reg = df["Annual_Spending"]

print("Regression target:")
display(y_reg.head())

categorical_features = [
    "Gender", "City_Tier", "Membership_Type", "Preferred_Category"
]

numeric_features = [
    "Age", "Income", "Tenure_Months", "Visits_Per_Month",
    "Products_Bought", "Avg_Order_Value", "Discount_Usage_Rate",
    "Cart_Abandonment_Rate", "Reviews_Given", "Support_Tickets",
    "Days_Since_Last_Purchase"
]

print("Categorical features:", categorical_features)
print("Numeric features:", numeric_features)

X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
    X_reg,
    y_reg,
    test_size=0.20,
    random_state=42
)

print("Training rows:", len(X_train_reg))
print("Testing rows:", len(X_test_reg))

# ==========================================================
# Topic: Linear Regression Pipeline
# Description:
# Pipeline connects preprocessing and Linear Regression into one workflow.
# The preprocessing happens first, followed by model training.
#
# Key idea:
# Linear Regression learns a mathematical relationship between the input features and Annual_Spending.
# ==========================================================

linear_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", LinearRegression())
])

print("Linear Regression pipeline created.")

preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numeric_features),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features),
    ],
    remainder="passthrough",
)

print("Preprocessor created.")

linear_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", LinearRegression())
])

print("Linear Regression pipeline created.")

linear_model.fit(X_train_reg, y_train_reg)

print("Linear Regression training completed.")

# ==========================================================
# Topic: Linear Regression Predictions
# Description:
# predict() uses the trained model to estimate Annual_Spending for the test customers.
#
# Key idea:
# The predicted values can now be compared with the actual values.
# ==========================================================

# Ensure linear_model is defined and fitted before making predictions
# This makes the cell robust to kernel state loss.
if 'linear_model' not in locals() and 'linear_model' not in globals():
    # Recreate preprocessor if it's also not defined (though it is in the current kernel state)
    if 'preprocessor' not in locals() and 'preprocessor' not in globals():
        from sklearn.compose import ColumnTransformer
        from sklearn.preprocessing import OneHotEncoder, StandardScaler
        from sklearn.pipeline import Pipeline
        from sklearn.linear_model import LinearRegression

        preprocessor = ColumnTransformer(
            transformers=[
                ("num", StandardScaler(), numeric_features),
                ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features),
            ],
            remainder="passthrough",
        )
        print("Preprocessor recreated for robustness.")

    linear_model = Pipeline([
        ("preprocessor", preprocessor),
        ("model", LinearRegression())
    ])
    linear_model.fit(X_train_reg, y_train_reg)
    print("Linear Regression pipeline recreated and trained for robustness.")

linear_pred = linear_model.predict(X_test_reg)

display(pd.DataFrame({
    "Actual": y_test_reg.values,
    "Predicted": linear_pred
}).head(10))

"""#### Regression Metrics"""

mae = mean_absolute_error(y_test_reg, linear_pred)
mse = mean_squared_error(y_test_reg, linear_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test_reg, linear_pred)

print(f"Mean Absolute Error (MAE): {mae:.2f}")
print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")
print(f"R-squared (R2): {r2:.2f}")

plt.figure(figsize=(8, 6))
plt.scatter(y_test_reg, linear_pred, alpha=0.75)

min_value = min(y_test_reg.min(), linear_pred.min())
max_value = max(y_test_reg.max(), linear_pred.max())

plt.plot(
    [min_value, max_value],
    [min_value, max_value],
    linestyle="--"
)

plt.xlabel("Actual Annual Spending (₹)")
plt.ylabel("Predicted Annual Spending (₹)")
plt.title("Linear Regression — Actual vs Predicted")
plt.show()

tree_reg_model = Pipeline([
    ("preprocessor", ColumnTransformer([
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
    ], remainder="passthrough")),
    ("model", DecisionTreeRegressor(max_depth=5, random_state=42))
])

print("Decision Tree Regressor created.")

# Ensure tree_reg_model is defined before fitting and predicting.
# This makes the cell robust to kernel state loss.
if 'tree_reg_model' not in locals() and 'tree_reg_model' not in globals():
    from sklearn.compose import ColumnTransformer
    from sklearn.preprocessing import OneHotEncoder
    from sklearn.pipeline import Pipeline
    from sklearn.tree import DecisionTreeRegressor

    tree_reg_model = Pipeline([
        ("preprocessor", ColumnTransformer([
            ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
        ], remainder="passthrough")),
        ("model", DecisionTreeRegressor(max_depth=5, random_state=42))
    ])
    print("Decision Tree Regressor pipeline recreated for robustness.")

tree_reg_model.fit(X_train_reg, y_train_reg)

tree_pred = tree_reg_model.predict(X_test_reg)

print("Predictions created:", len(tree_pred))

tree_mae = mean_absolute_error(y_test_reg, tree_pred)
tree_rmse = np.sqrt(mean_squared_error(y_test_reg, tree_pred))
tree_r2 = r2_score(y_test_reg, tree_pred)

print(f"MAE  : ₹{tree_mae:,.2f}")
print(f"RMSE : ₹{tree_rmse:,.2f}")
print(f"R²   : {tree_r2:.3f}")

forest_reg_model.fit(X_train_reg, y_train_reg)

forest_pred = forest_reg_model.predict(X_test_reg)

print("Predictions created:", len(forest_pred))

forest_mae = mean_absolute_error(y_test_reg, forest_pred)
forest_rmse = np.sqrt(mean_squared_error(y_test_reg, forest_pred))
forest_r2 = r2_score(y_test_reg, forest_pred)

print(f"MAE  : ₹{forest_mae:,.2f}")
print(f"RMSE : ₹{forest_rmse:,.2f}")
print(f"R²   : {forest_r2:.3f}")

linear_mae = mae
linear_rmse = rmse
linear_r2 = r2

regression_results = pd.DataFrame([
    {
        "Model": "Linear Regression",
        "MAE": linear_mae,
        "RMSE": linear_rmse,
        "R²": linear_r2
    },
    {
        "Model": "Decision Tree",
        "MAE": tree_mae,
        "RMSE": tree_rmse,
        "R²": tree_r2
    },
    {
        "Model": "Random Forest",
        "MAE": forest_mae,
        "RMSE": forest_rmse,
        "R²": forest_r2
    }
])

display(regression_results.round(3))

residuals = y_test_reg - forest_pred

display(residuals.head())

plt.figure(figsize=(8, 5))
plt.scatter(forest_pred, residuals, alpha=0.75)
plt.axhline(0, linestyle="--")
plt.xlabel("Predicted Annual Spending (₹)")
plt.ylabel("Residual (Actual - Predicted)")
plt.title("Random Forest Regression Residuals")
plt.show()

classification_features = regression_features.copy()

X_clf = df[classification_features]
print("Number of input features:", X_clf.shape[1])

y_clf = df["Churn"]

display(y_clf.head())

X_train_clf, X_test_clf, y_train_clf, y_test_clf = train_test_split(
    X_clf,
    y_clf,
    test_size=0.20,
    random_state=42,
    stratify=y_clf
)

print("Training rows:", len(X_train_clf))
print("Testing rows:", len(X_test_clf))

logistic_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", LogisticRegression(max_iter=1000, random_state=42))
])

print("Logistic Regression pipeline created.")

logistic_model.fit(X_train_clf, y_train_clf)

logistic_pred = logistic_model.predict(X_test_clf)
logistic_prob = logistic_model.predict_proba(X_test_clf)[:, 1]

print("First 10 predicted classes:", logistic_pred[:10])
print("First 10 churn probabilities:", logistic_prob[:10])

logistic_accuracy = accuracy_score(y_test_clf, logistic_pred)
logistic_precision = precision_score(y_test_clf, logistic_pred, zero_division=0)
logistic_recall = recall_score(y_test_clf, logistic_pred, zero_division=0)
logistic_f1 = f1_score(y_test_clf, logistic_pred, zero_division=0)
logistic_auc = roc_auc_score(y_test_clf, logistic_prob)

print(f"Accuracy : {logistic_accuracy:.3f}")
print(f"Precision: {logistic_precision:.3f}")
print(f"Recall   : {logistic_recall:.3f}")
print(f"F1-score : {logistic_f1:.3f}")
print(f"ROC-AUC  : {logistic_auc:.3f}")

threshold = 0.50

threshold_pred = (logistic_prob >= threshold).astype(int)

print("Threshold:", threshold)
print("First 10 predictions:", threshold_pred[:10])

for threshold in [0.30, 0.50, 0.70]:
    threshold_pred = (logistic_prob >= threshold).astype(int)

    print(f"Threshold = {threshold:.2f}")
    print(
        f"Precision = {precision_score(y_test_clf, threshold_pred, zero_division=0):.3f}"
    )
    print(
        f"Recall    = {recall_score(y_test_clf, threshold_pred, zero_division=0):.3f}"
    )
    print()